
CREATE TABLE users(
	id INT AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    occupation VARCHAR(255) NOT NULL
);

CREATE TABLE subjects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    active INT NOT NULL DEFAULT 1
);

